[workspace]
members = [
    "bytes",
    "communication",
    "kafkaesque",
    "logging",
#    "sort",
    "timely",
]

[profile.release]
opt-level = 3
rpath = false
lto = true
debug-assertions = false
